//game alarm listener

public interface GameAlarmListener extends AlarmListener {
	//
	//	The takeNotice method is meant to respond to events associated with,
	//		or actions generated by, an Alarm.
	//
	public void takeNotice();
}
